### ISSUE TITLE
Add example of encrypting field nested in an array

### ISSUE THREAD

**Issue by ctrimble** [meltmedia/dropwizard-crypto#5]
We recently had trouble encrypting a password nested under the `/metrics/reporters` path, using the provided instructions.  This seems like a common use case and should be addressed by an example and an automated test.

We could run the following process:

- define which field was encrypted, using a mixin.
- encrypt the value, using the provided instructions, in a separate file.
- copy and paste the generated value into the configuration file.
- launch the app.

We could not:

- write the clear text value into the configuration file.
- generate an encrypted form of the configuration file using the clear text form of the configuration file and a JSON pointer to the field requiring encryption.

**Comment by anazri** [comment]
Hi @ctrimble 

I got the following error when try to run the original app. please advice.

Exception in thread "main" com.meltmedia.jackson.crypto.EncryptionException: could not create encryption cypher
	at com.meltmedia.jackson.crypto.EncryptionService.createEncryptionCipher(EncryptionService.java:282)
	at com.meltmedia.jackson.crypto.EncryptionService.encrypt(EncryptionService.java:334)
	at com.meltmedia.jackson.crypto.EncryptionService.encrypt(EncryptionService.java:361)
	at com.meltmedia.jackson.crypto.EncryptionService.encryptValue(EncryptionService.java:372)
	at com.meltmedia.dropwizard.crypto.Commands$Encrypt.run(Commands.java:116)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:72)
	at com.meltmedia.dropwizard.crypto.example.CryptoApplication.main(CryptoApplication.java:28)
Caused by: java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at com.meltmedia.jackson.crypto.EncryptionService.createEncryptionCipher(EncryptionService.java:276)
